# Generated by Django 3.2.6 on 2022-04-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project',
            new_name='blog',
        ),
    ]
