# Generated by Django 3.2.6 on 2022-04-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20220412_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
    ]
